# Version for this file.
version: 1

# The OS to compile for. `GOOS` env variable will be set to this value.
goos: linux


# The architecture to compile for. `GOARCH` env variable will be set to this value.
goarch: amd64


# (Optional) Entrypoint to compile.
# main: ./path/to/main.go

# (Optional) Working directory. (default: root of the project)
# dir: ./relative/path/to/dir

# Binary output name.
# {{ .Os }} will be replaced by goos field in the config file.
# {{ .Arch }} will be replaced by goarch field in the config file.
binary: kacti-{{ .Os }}-{{ .Arch }}

ldflags:
  - "-X github.com/shaneboulden/kacti/cmd.Version={{ .Env.VERSION }}"
  - "-X github.com/shaneboulden/kacti/cmd.Commit={{ .Env.COMMIT }}"
  - "-X github.com/shaneboulden/kacti/cmd.CommitDate={{ .Env.COMMIT_DATE }}"
  - "-X github.com/shaneboulden/kacti/cmd.TreeState={{ .Env.TREE_STATE }}"