name: CycloneDX SBOM generate
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  generate:
    name: CycloneDX GoMod Generate SBOM
    uses: CycloneDX/gh-gomod-generate-sbom@v2.0.0
    with:
      args: mod -licenses -json -output bom.json
